
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pranav
 */
public class LOGIN_PAGE extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
 
static String pname=null;
    /**
     * Creates new form LOGIN_PAGE
     */
    public LOGIN_PAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        BuyTab = new javax.swing.JTabbedPane();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        product_name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pro_name = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        dtotal1 = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        Login1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        balance2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        Log_Out1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));

        BuyTab.setBackground(new java.awt.Color(20, 20, 20));
        BuyTab.setForeground(new java.awt.Color(51, 51, 155));

        jInternalFrame6.setBackground(new java.awt.Color(20, 20, 20));
        jInternalFrame6.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(20, 20, 20));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(null);

        Login.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 0, 153));
        Login.setText("Exit");
        Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.setOpaque(false);
        Login.setSelected(true);
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel2.add(Login);
        Login.setBounds(1110, 40, 60, 30);

        product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_nameActionPerformed(evt);
            }
        });
        jPanel2.add(product_name);
        product_name.setBounds(310, 30, 220, 30);

        jButton2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(550, 30, 81, 30);

        pro_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_nameActionPerformed(evt);
            }
        });
        jPanel2.add(pro_name);
        pro_name.setBounds(270, 100, 170, 30);
        jPanel2.add(quantity);
        quantity.setBounds(460, 100, 150, 30);

        balance.setEnabled(false);
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        jPanel2.add(balance);
        balance.setBounds(560, 260, 90, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Buy Items");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 200, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Your Total:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(320, 260, 90, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("List of Products:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 130, 129, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(270, 80, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Available Quantity");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(460, 80, 120, 20);

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(560, 170, 80, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("Price");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(630, 80, 90, 20);

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 255));
        jLabel51.setText("Enter Qty:");
        jPanel2.add(jLabel51);
        jLabel51.setBounds(320, 180, 90, 20);

        price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price1ActionPerformed(evt);
            }
        });
        jPanel2.add(price1);
        price1.setBounds(630, 100, 120, 30);

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        jPanel2.add(qty);
        qty.setBounds(410, 170, 90, 30);

        jButton3.setText("Buy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(460, 320, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 160, 180, 290);

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(460, 380, 80, 30);

        dtotal1.setEnabled(false);
        dtotal1.setInheritsPopupMenu(true);
        dtotal1.setRequestFocusEnabled(false);
        dtotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtotal1ActionPerformed(evt);
            }
        });
        jPanel2.add(dtotal1);
        dtotal1.setBounds(410, 260, 90, 30);

        javax.swing.GroupLayout jInternalFrame6Layout = new javax.swing.GroupLayout(jInternalFrame6.getContentPane());
        jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
        jInternalFrame6Layout.setHorizontalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame6Layout.setVerticalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BuyTab.addTab("Buy", jInternalFrame6);

        jInternalFrame1.setBackground(new java.awt.Color(20, 20, 20));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(600, 400));
        jInternalFrame1.setVisible(true);

        jPanel3.setBackground(new java.awt.Color(20, 20, 20));
        jPanel3.setForeground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(null);

        Login1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Login1.setForeground(new java.awt.Color(0, 0, 153));
        Login1.setText("Back");
        Login1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login1.setOpaque(false);
        Login1.setSelected(true);
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        jPanel3.add(Login1);
        Login1.setBounds(1180, 50, 60, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel22);
        jLabel22.setBounds(400, 370, 170, 30);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel25);
        jLabel25.setBounds(400, 370, 170, 30);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel26);
        jLabel26.setBounds(400, 330, 170, 30);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel27);
        jLabel27.setBounds(400, 290, 170, 30);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel29);
        jLabel29.setBounds(910, 250, 200, 30);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel30);
        jLabel30.setBounds(400, 490, 170, 30);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel31);
        jLabel31.setBounds(400, 530, 170, 30);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel32);
        jLabel32.setBounds(400, 490, 170, 30);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel33);
        jLabel33.setBounds(160, 320, 170, 30);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel34);
        jLabel34.setBounds(400, 410, 170, 30);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel35);
        jLabel35.setBounds(400, 530, 170, 30);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel36);
        jLabel36.setBounds(910, 290, 200, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Pincode:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 280, 90, 30);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 255));
        jLabel37.setText("Last Name:");
        jPanel3.add(jLabel37);
        jLabel37.setBounds(20, 120, 90, 30);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 255));
        jLabel38.setText("Date of Birth:");
        jPanel3.add(jLabel38);
        jLabel38.setBounds(20, 160, 110, 30);

        jLabel39.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 255));
        jLabel39.setText("Mobile No.:");
        jPanel3.add(jLabel39);
        jLabel39.setBounds(20, 200, 90, 30);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 255));
        jLabel40.setText("Country:");
        jPanel3.add(jLabel40);
        jLabel40.setBounds(20, 360, 90, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("State:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 320, 90, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Address:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 240, 90, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("First Name:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 80, 100, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("E-mail Id:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(500, 80, 100, 30);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel41);
        jLabel41.setBounds(160, 200, 170, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("Username:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(500, 120, 100, 30);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel42);
        jLabel42.setBounds(160, 160, 170, 30);

        jLabel43.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel43);
        jLabel43.setBounds(160, 200, 170, 30);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel44);
        jLabel44.setBounds(160, 160, 170, 30);

        jLabel45.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel45);
        jLabel45.setBounds(160, 120, 170, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel19);
        jLabel19.setBounds(670, 80, 200, 30);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel20);
        jLabel20.setBounds(160, 320, 170, 30);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel21);
        jLabel21.setBounds(160, 360, 170, 30);

        jLabel46.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel46);
        jLabel46.setBounds(160, 320, 170, 30);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel23);
        jLabel23.setBounds(160, 280, 170, 30);

        jLabel47.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel47);
        jLabel47.setBounds(160, 240, 170, 30);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel48);
        jLabel48.setBounds(160, 360, 170, 30);

        jLabel49.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel49);
        jLabel49.setBounds(670, 120, 200, 30);

        jLabel50.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 255));
        jPanel3.add(jLabel50);
        jLabel50.setBounds(160, 80, 170, 30);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BuyTab.addTab("Profile", jInternalFrame1);

        jInternalFrame4.setBackground(new java.awt.Color(20, 20, 20));
        jInternalFrame4.setVisible(true);

        jPanel4.setBackground(new java.awt.Color(20, 20, 20));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("Enter amount to be added:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(70, 170, 190, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("Your Current Balance:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(80, 80, 160, 30);

        balance2.setEnabled(false);
        balance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balance2ActionPerformed(evt);
            }
        });
        jPanel4.add(balance2);
        balance2.setBounds(270, 80, 90, 30);

        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("Update");
        jButton5.setBorderPainted(false);
        jButton5.setDoubleBuffered(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(410, 180, 80, 30);

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel4.add(amount);
        amount.setBounds(270, 170, 90, 30);

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1);
        jRadioButton1.setBounds(120, 280, 93, 23);

        jRadioButton2.setText("jRadioButton2");
        jPanel4.add(jRadioButton2);
        jRadioButton2.setBounds(120, 310, 93, 23);

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BuyTab.addTab("Balance", jInternalFrame4);

        jInternalFrame5.setBackground(new java.awt.Color(20, 20, 20));
        jInternalFrame5.setVisible(true);

        jPanel5.setBackground(new java.awt.Color(20, 20, 20));

        jLabel24.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 255));
        jLabel24.setText("shashankvthakur@gmail.com");

        jLabel28.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 255));
        jLabel28.setText("Email Us at:");

        jLabel52.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 255));
        jLabel52.setText("Version");

        jLabel53.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 255));
        jLabel53.setText("vswapneel27@gmail.com");

        jLabel54.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 255));
        jLabel54.setText("sanchit7v@gmail.com");

        jLabel55.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(51, 51, 255));
        jLabel55.setText("Virtual_Market_1.0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel55)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 196, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54)
                    .addComponent(jLabel24)
                    .addComponent(jLabel53))
                .addGap(467, 467, 467))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel52))
                .addGap(54, 54, 54)
                .addComponent(jLabel28)
                .addGap(4, 4, 4)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
        jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
        jInternalFrame5Layout.setHorizontalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame5Layout.setVerticalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BuyTab.addTab("Help Centre", jInternalFrame5);

        Log_Out1.setBackground(new java.awt.Color(102, 102, 102));
        Log_Out1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Log_Out1.setForeground(new java.awt.Color(0, 0, 102));
        Log_Out1.setText("Log Out");
        Log_Out1.setBorder(new javax.swing.border.MatteBorder(null));
        Log_Out1.setHideActionText(true);
        Log_Out1.setSelected(true);
        Log_Out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_Out1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(BuyTab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Log_Out1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(BuyTab, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Log_Out1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(Log_Out1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuyTab, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Log_Out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_Out1ActionPerformed
        new MAIN_PAGE().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Log_Out1ActionPerformed
      
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
         String sql ="select Product_Name from stock";  
      try{
      con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
      pst=con.prepareStatement(sql);
      rs=pst.executeQuery();
      jTable1.setModel(DbUtils.resultSetToTableModel(rs));
      }
      catch(HeadlessException | SQLException ex)
	        {
	        	JOptionPane.showMessageDialog(null,"GENERAL EXCEPTION", "WARNING!!!",JOptionPane.INFORMATION_MESSAGE);
	        	}  
        
      String sql1 = "select * from regs where Username= ? ";
        try{
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
            PreparedStatement pst = con.prepareStatement(sql1);
            MAIN_PAGE m1=new MAIN_PAGE();
            pst.setString(1, m1.username);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("First_name");
                jLabel50.setText(add1);
                String add2 = rs.getString("Last_name");
                jLabel45.setText(add2);
                String add3 = rs.getString("DoB");
                jLabel42.setText(add3);
                String add4 = rs.getString("Mobile_No");
                jLabel41.setText(add4);
                String add5 = rs.getString("Address");
                jLabel47.setText(add5);
                String add6 = rs.getString("Pincode");
                jLabel23.setText(add6);
                String add7 = rs.getString("State");
                jLabel33.setText(add7);
                String add8 = rs.getString("Country");
                jLabel21.setText(add8);
                String add9 = rs.getString("Email_ID");
                jLabel19.setText(add9);
                String add10 = rs.getString("Username");
                jLabel49.setText(add10);
                }
            else{
                JOptionPane.showMessageDialog(null,"Data not Found");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }  
        
        
        
         String sql2 = "select Balance from regs where Username= ? ";
        try{
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
            PreparedStatement pst = con.prepareStatement(sql2);
            MAIN_PAGE m1=new MAIN_PAGE();
            pst.setString(1, m1.username);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String x = rs.getString("Balance");
                balance.setText(x);
               // String x2 = rs.getString("Balance");
                balance2.setText(x);
                }
            else{
                JOptionPane.showMessageDialog(null,"Data not Found");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }  
        
        
     // TODO add your handling code here:      
     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
        new LOGIN_PAGE().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Login1ActionPerformed

    private void dtotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtotal1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new LOGIN_PAGE().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int qty1=Integer.parseInt(qty.getText());
        int qtyold=Integer.parseInt(quantity.getText());
        int qtynew=qtyold-qty1;
        if(qtynew<0){
            JOptionPane.showMessageDialog(null, "Not enough products in stock.");
            new LOGIN_PAGE().setVisible(true);
            dispose();
        }
        else{
            String DBqtynew=String.valueOf(qtynew);

            String sql = "UPDATE stock set Quantity=? where Product_Name=?";
            try{
                con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
                pst = con.prepareStatement(sql);

                pst.setString(1,DBqtynew);
                pst.setString(2,pro_name.getText());
                //pst.setString(1, price1.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Order Placed");
                //new LOGIN_PAGE().setVisible(true);
                //dispose();
            }
            catch (  HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }

        int oldbal=Integer.parseInt(balance.getText());
        int amount=Integer.parseInt(dtotal1.getText());
        int newbal=oldbal-amount;
        if(oldbal<amount)
        {
            JOptionPane.showMessageDialog(null, "Not enough balance");
            new LOGIN_PAGE().setVisible(true);
            dispose();
        }
        else
        {
            String sql3 = "UPDATE regs set Balance=? where Username=?";
            try{
                String newbalance=String.valueOf(newbal);
                con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
                pst = con.prepareStatement(sql3);
                MAIN_PAGE m2=new MAIN_PAGE();
                pst.setString(1,newbalance);
                pst.setString(2, m2.username);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Your new balance is "+newbalance);
                new LOGIN_PAGE().setVisible(true);
                dispose();
            }
            catch (  HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int quantity=0;

        if(pname!=null )
        {
            quantity = Integer.parseInt(qty.getText());

        }

        int price2=Integer.parseInt(price1.getText());
        int total=quantity*price2;
        dtotal1.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void pro_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pname = (product_name.getText());
        String sql = "select * from stock where Product_Name= ? ";
        try{
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, pname);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("Product_Name");
                pro_name.setText(add1);
                String add2 = rs.getString("Quantity");
                quantity.setText(add2);
                String add3 = rs.getString("Price");
                price1.setText(add3);
            }
            else{
                JOptionPane.showMessageDialog(null,"Data not Found");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_nameActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        new LOGIN_PAGE().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void balance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balance2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balance2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int oldbal=Integer.parseInt(balance2.getText());
        int amt=Integer.parseInt(amount.getText());
        int new_bal=oldbal+amt;
            String sql4 = "UPDATE regs set Balance=? where Username=?";
            try{
                String newbal1=String.valueOf(new_bal);
                con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
                pst = con.prepareStatement(sql4);
                MAIN_PAGE m2=new MAIN_PAGE();
                pst.setString(1,newbal1);
                pst.setString(2, m2.username);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Your new balance is "+newbal1);
                new LOGIN_PAGE().setVisible(true);
                dispose();
            }
            catch (  HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_PAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BuyTab;
    private javax.swing.JButton Log_Out1;
    private javax.swing.JButton Login;
    private javax.swing.JButton Login1;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField balance2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dtotal1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField pro_name;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
