import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

public class New_User extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
 
    /**
     * Creates new form New_User
     */
    public New_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Last_name = new javax.swing.JTextField();
        DoB = new javax.swing.JTextField();
        Mobile_No = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        State = new javax.swing.JTextField();
        Pincode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        First_name = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Email_Id = new javax.swing.JTextField();
        Lets_start = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Reenter_Password1 = new javax.swing.JPasswordField();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(20, 20, 20));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Pincode:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 460, 90, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Re-enter Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(570, 390, 160, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Last Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 300, 90, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Date of Birth:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 340, 110, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Mobile No.:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 380, 90, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Country:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 540, 90, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("State:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 500, 90, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Address:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 420, 90, 30);

        Country.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Country);
        Country.setBounds(240, 540, 170, 30);

        Username.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Username);
        Username.setBounds(760, 300, 220, 30);

        Last_name.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Last_name);
        Last_name.setBounds(240, 300, 170, 30);

        DoB.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(DoB);
        DoB.setBounds(240, 340, 170, 30);

        Mobile_No.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Mobile_No);
        Mobile_No.setBounds(240, 380, 170, 30);

        Address.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Address);
        Address.setBounds(240, 420, 170, 30);

        State.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(State);
        State.setBounds(240, 500, 170, 30);

        Pincode.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(Pincode);
        Pincode.setBounds(240, 460, 170, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("First Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 260, 100, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("E-mail Id:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(570, 260, 100, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("Create Password:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(570, 350, 140, 30);

        First_name.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(First_name);
        First_name.setBounds(240, 260, 170, 30);

        Password.setBackground(new java.awt.Color(204, 204, 255));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password);
        Password.setBounds(760, 350, 220, 30);

        Email_Id.setBackground(new java.awt.Color(204, 204, 255));
        Email_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Email_Id);
        Email_Id.setBounds(760, 260, 250, 30);

        Lets_start.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Lets_start.setForeground(new java.awt.Color(51, 51, 255));
        Lets_start.setText("Let's Start");
        Lets_start.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Lets_start.setOpaque(false);
        Lets_start.setSelected(true);
        Lets_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lets_startActionPerformed(evt);
            }
        });
        jPanel1.add(Lets_start);
        Lets_start.setBounds(450, 640, 90, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Enter your details:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(440, 180, 150, 50);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Create your User Id");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 140, 320, 50);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 255));
        jLabel15.setText("Username:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(570, 300, 100, 30);

        Reenter_Password1.setBackground(new java.awt.Color(204, 204, 255));
        Reenter_Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reenter_Password1ActionPerformed(evt);
            }
        });
        jPanel1.add(Reenter_Password1);
        Reenter_Password1.setBounds(760, 390, 220, 30);

        Back.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Back.setForeground(new java.awt.Color(102, 102, 255));
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(900, 70, 90, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void Email_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_IdActionPerformed

    private void Lets_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lets_startActionPerformed
        if(First_name.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "First Name is Required!!!");
            First_name.requestFocus();
        }
        else if
        (Last_name.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Last Name is Required!!!");
            Last_name.requestFocus();
        }
        else if
        (DoB.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Date of Birth is Required!!!");
            DoB.requestFocus();
        }
        else if
        (Mobile_No.getText().length()!=10)
        {
            JOptionPane.showMessageDialog(this, "Please enter 10 digits mobile number!!!");
            Mobile_No.requestFocus();
        }
        else if
        (Address.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Address is Required!!!");
            Address.requestFocus();
        }
        else if
        (Pincode.getText().length()!=6)
        {
            JOptionPane.showMessageDialog(this, "6 digits Pincode is Required!!!");
            Pincode.requestFocus();
        }
        else if
        (State.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "State is Required!!!");
            State.requestFocus();
        }
        else if
        (Country.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Country is Required!!!");
            Country.requestFocus();
        }
        else if
        (Email_Id.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Email Id is Required!!!");
            Email_Id.requestFocus();
        }
        else if
        (Username.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this, "Username is Required!!!");
            Username.requestFocus();
        }
        else if
        (Password.getText().length()<8)
        {
            JOptionPane.showMessageDialog(this, "Password is Required!!!");
            Password.requestFocus();
        }
        //else if (8<=Reenter_Password1.getText().length())
        else
        {
            
            if(Reenter_Password1.getText().length()<8)
            {
            JOptionPane.showMessageDialog(this, "Confirm Password required!!!");
            Reenter_Password1.requestFocus();
            }
            else{  
            JPasswordField s1;
           // s1 = null;
            s1=Password;
          //  String pwd= JPasswordField s1;
            JPasswordField s2;
            s2 = Reenter_Password1;
            if(s1.equals(s2))
            {
               // JOptionPane.showMessageDialog(this, "Password saved!");
                //Password.requestFocus(); 
                String sql = "Insert into regs (First_name, Last_name, DoB, Mobile_No, Address, Pincode, State, Country, Email_Id, Username, Password) values(?, ?, ?, ?, ?, ?,?, ?, ?,?, ?)";
                try{
                con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
                pst = con.prepareStatement(sql);
                pst.setString(1, First_name.getText());
                pst.setString(2, Last_name.getText());
                pst.setString(3, DoB.getText());
                pst.setString(4, Mobile_No.getText());
                pst.setString(5, Address.getText());
                pst.setString(6, Pincode.getText());
                pst.setString(7, State.getText());
                pst.setString(8, Country.getText());
                pst.setString(9, Email_Id.getText());
                pst.setString(10, Username.getText());
                pst.setString(11, Password.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved");

                new MAIN_PAGE().setVisible(true);
                dispose();
                }
                catch (  HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this, "Invalid Password! Reenter Password");
                Reenter_Password1.requestFocus();
            }
            }
            
        }
/*        else{

            String sql = "Insert into regs (First_name, Last_name, DoB, Mobile_No, Address, Pincode, State, Country, Email_Id, Username, Password) values(?, ?, ?, ?, ?, ?,?, ?, ?,?, ?)";
            try{
                con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\admin\\Documents\\NetBeansProjects\\OOPM_Project_Latest\\OOPM_Project_Latest\\OOPM\\db\\VirtualMarketDB.accdb");
                pst = con.prepareStatement(sql);
                pst.setString(1, First_name.getText());
                pst.setString(2, Last_name.getText());
                pst.setString(3, DoB.getText());
                pst.setString(4, Mobile_No.getText());
                pst.setString(5, Address.getText());
                pst.setString(6, Pincode.getText());
                pst.setString(7, State.getText());
                pst.setString(8, Country.getText());
                pst.setString(9, Email_Id.getText());
                pst.setString(10, Username.getText());
                pst.setString(11, Password.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved");

                new MAIN_PAGE().setVisible(true);
                dispose();
            }
            catch (  HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }

        }*/
    }//GEN-LAST:event_Lets_startActionPerformed

    private void Reenter_Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reenter_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reenter_Password1ActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new MAIN_PAGE().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new New_User().setVisible(true);
        });
    }

        
        
        
        
        
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel Back;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField DoB;
    private javax.swing.JTextField Email_Id;
    private javax.swing.JTextField First_name;
    private javax.swing.JTextField Last_name;
    private javax.swing.JButton Lets_start;
    private javax.swing.JTextField Mobile_No;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Pincode;
    private javax.swing.JPasswordField Reenter_Password1;
    private javax.swing.JTextField State;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
